# Generated by Django 5.2.5 on 2025-08-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionrecord_boites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='boites_produites',
            field=models.PositiveIntegerField(default=0, verbose_name='Boîtes Produites'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='dechets_boites',
            field=models.PositiveIntegerField(default=0, verbose_name='Déchets Boîtes'),
        ),
    ]
