# Generated by Django 5.2.5 on 2025-09-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_productionrecord_boites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletteNonConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_palette', models.DateField()),
                ('quantite_non_conforme', models.IntegerField()),
                ('operateur', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de contrôle'), ('conforme', 'Devenue conforme'), ('non_conforme', 'Reste non conforme')], default='en_attente', max_length=20)),
                ('quantite_conforme_apres_controle', models.IntegerField(default=0)),
                ('date_controle', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'palette_non_conforme',
            },
        ),
    ]
