# Generated by Django 5.2.5 on 2025-09-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_palettenonconforme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaletteNonConforme',
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='commentaire_controle',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire contrôle'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='date_controle_nc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date contrôle NC'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='fardeaux_conformes_apres_controle',
            field=models.PositiveIntegerField(default=0, verbose_name='Fardeaux conformes après contrôle'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='statut_palette_nc',
            field=models.CharField(choices=[('en_attente', 'En attente de contrôle'), ('traitee', 'Traitée')], default='en_attente', max_length=20, verbose_name='Statut Palettes NC'),
        ),
    ]
