# Generated by Django 5.2.5 on 2025-09-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_delete_palettenonconforme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrecord',
            name='commentaire_controle',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='fardeaux_conformes_apres_controle',
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='commentaire_controle_nc',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire contrôle NC'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='fardeaux_recuperes',
            field=models.PositiveIntegerField(default=0, verbose_name='Fardeaux récupérés'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='date_controle_nc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du contrôle NC'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='statut_palette_nc',
            field=models.CharField(choices=[('en_attente', 'En attente de traitement'), ('traitee', 'Traitée - Toutes conformes'), ('partiel', 'Traitement partiel'), ('rejetee', 'Confirmées non conformes'), ('conforme', 'Toutes conformes dès le départ')], default='en_attente', max_length=20, verbose_name='Statut palettes NC'),
        ),
    ]
