# Generated by Django 5.2.5 on 2025-09-19 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_remove_productionrecord_commentaire_controle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire_equipe', models.CharField(blank=True, choices=[('6-14', '6h - 14h (Équipe du Matin)'), ('14-22', "14h - 22h (Équipe de l'Après-midi)"), ('22-6', '22h - 6h (Équipe de Nuit)')], help_text="Définit les heures d'accès autorisées pour cet utilisateur", max_length=10, null=True, verbose_name="Horaire d'équipe")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Profil actif')),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
                'ordering': ['user__username'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'ordering': ['horaire', 'nom'], 'verbose_name': 'Équipe', 'verbose_name_plural': 'Équipes'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AddField(
            model_name='alerte',
            name='commentaire_resolution',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de résolution'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='priorite',
            field=models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Équipe active'),
        ),
        migrations.AddField(
            model_name='ligneproduction',
            name='capacite_theorique',
            field=models.PositiveIntegerField(default=0, help_text='Capacité de production théorique par heure', verbose_name='Capacité théorique (palettes/h)'),
        ),
        migrations.AddField(
            model_name='ligneproduction',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ligneproduction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='produit',
            name='code_produit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Produit actif'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='message',
            field=models.TextField(verbose_name="Message d'alerte"),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='production_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='production.productionrecord', verbose_name='Enregistrement de production'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('arret', 'Arrêt de production'), ('dechets', 'Niveau de déchets élevé'), ('qualite', 'Problème qualité'), ('maintenance', 'Maintenance requise'), ('conformite', 'Non-conformité'), ('performance', 'Performance dégradée'), ('other', 'Autre')], default='other', max_length=20, verbose_name="Type d'alerte"),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='horaire',
            field=models.CharField(choices=[('6-14', '6h - 14h (Équipe du Matin)'), ('14-22', "14h - 22h (Équipe de l'Après-midi)"), ('22-6', '22h - 6h (Équipe de Nuit)')], max_length=10, verbose_name='Horaire de travail'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=100, verbose_name="Nom de l'équipe"),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur responsable'),
        ),
        migrations.AlterField(
            model_name='ligneproduction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ligne active'),
        ),
        migrations.AlterField(
            model_name='ligneproduction',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la ligne'),
        ),
        migrations.AlterField(
            model_name='ligneproduction',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Numéro de ligne'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='boites_produites',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de boîtes produites', verbose_name='Boîtes Produites'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='cause_arret',
            field=models.TextField(blank=True, help_text='Description de la cause des arrêts', null=True, verbose_name="Cause de l'Arrêt"),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='commentaire_controle_nc',
            field=models.TextField(blank=True, help_text='Détails du traitement des palettes non conformes', null=True, verbose_name='Commentaire contrôle NC'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='commentaires',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaires généraux'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='date_controle_nc',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le contrôle NC a été effectué', null=True, verbose_name='Date du contrôle NC'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='date_heure',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure de l'enregistrement", verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='dechets_boites',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de boîtes mises au rebut (incluant traitements NC)', verbose_name='Déchets Boîtes'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='duree_arret_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Durée totale des arrêts en minutes', verbose_name="Durée d'Arrêt (minutes)"),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.equipe', verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='fardeaux_recuperes',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de fardeaux récupérés lors du traitement NC', verbose_name='Fardeaux récupérés'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Enregistrement actif'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='palettes_non_conformes',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de palettes identifiées comme non conformes', verbose_name='Palettes Non Conformes'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='palettes_produites',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de palettes produites', verbose_name='Palettes Produites'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.produit', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='statut_palette_nc',
            field=models.CharField(choices=[('en_attente', 'En attente de traitement'), ('traitee', 'Traitée - Toutes conformes'), ('partiel', 'Traitement partiel'), ('rejetee', 'Confirmées non conformes'), ('conforme', 'Toutes conformes dès le départ')], default='en_attente', help_text='Statut du traitement des palettes non conformes', max_length=20, verbose_name='Statut palettes NC'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du produit'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['is_resolved', '-date_creation'], name='production__is_reso_f515e3_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['type_alerte', '-date_creation'], name='production__type_al_183fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['priorite', '-date_creation'], name='production__priorit_b5837d_idx'),
        ),
        migrations.AddIndex(
            model_name='productionrecord',
            index=models.Index(fields=['-date_heure'], name='production__date_he_18ae25_idx'),
        ),
        migrations.AddIndex(
            model_name='productionrecord',
            index=models.Index(fields=['ligne_production', '-date_heure'], name='production__ligne_p_58ef7a_idx'),
        ),
        migrations.AddIndex(
            model_name='productionrecord',
            index=models.Index(fields=['operateur', '-date_heure'], name='production__operate_7f1e26_idx'),
        ),
        migrations.AddIndex(
            model_name='productionrecord',
            index=models.Index(fields=['statut_palette_nc'], name='production__statut__e62190_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
