# Generated by Django 5.2.5 on 2025-08-26 00:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ligne de Production',
                'verbose_name_plural': 'Lignes de Production',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('horaire', models.CharField(choices=[('6-14', '6h - 14h (Équipe du Matin)'), ('14-22', "14h - 22h (Équipe de l'Après-midi)"), ('22-6', '22h - 6h (Équipe de Nuit)')], max_length=10)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'unique_together': {('operateur', 'horaire')},
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now)),
                ('palettes_produites', models.PositiveIntegerField(default=0, verbose_name='Palettes Produites')),
                ('dechets_boites', models.FloatField(default=0, verbose_name='Déchets (boites)')),
                ('duree_arret_minutes', models.PositiveIntegerField(default=0, verbose_name="Durée d'Arrêt (minutes)")),
                ('cause_arret', models.TextField(blank=True, null=True, verbose_name="Cause de l'Arrêt")),
                ('is_active', models.BooleanField(default=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.equipe')),
                ('ligne_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ligneproduction', verbose_name='Ligne de Production')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.produit')),
            ],
            options={
                'verbose_name': 'Enregistrement de Production',
                'verbose_name_plural': 'Enregistrements de Production',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('arret', 'Arrêt de production'), ('qualite', 'Problème qualité'), ('maintenance', 'Maintenance requise'), ('other', 'Autre')], default='arret', max_length=20)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('production_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='production.productionrecord')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
