# Generated by Django 5.2.5 on 2025-08-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='boites_produites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='dechets_boites',
            field=models.IntegerField(default=0),
        ),
    ]
