# Generated by Django 5.2.5 on 2025-08-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionrecord_boites_produites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='boites',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='palettes_non_conformes',
            field=models.PositiveIntegerField(default=0, verbose_name='Palettes Non Conformes'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('arret', 'Arrêt de production'), ('qualite', 'Problème qualité'), ('maintenance', 'Maintenance requise'), ('conformite', 'Non-conformité'), ('other', 'Autre')], default='arret', max_length=20),
        ),
    ]
