# Generated by Django 5.2.5 on 2025-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_productionrecord_boites_produites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrecord',
            name='boites',
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='cause_non_conformite',
            field=models.TextField(blank=True, help_text='Détaillez les raisons des palettes non conformes', null=True, verbose_name='Cause des Non-Conformités'),
        ),
    ]
